Update the GH workflows to 18.04 (from 16.04)
This is in response to the warning that's been given for a while:

> Warning: setup-php will stop working on Ubuntu 16.04 from August 1, 2021. Please upgrade to Ubuntu 18.04 or Ubuntu 20.04 - https://setup-php.com/i/452

Which is now a hard error causing builds to fail:

> Error: setup-php is not supported on Ubuntu 16.04. Please upgrade to Ubuntu 18.04 or Ubuntu 20.04 - https://setup-php.com/i/452